import { defineCollection, z } from 'astro:content';

const reviews = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string().max(65),
    description: z.string().max(160),
    primaryKeyword: z.string(),
    hub: z.string(),
    pageType: z.enum(['comparison', 'roundup', 'single_review', 'buying_guide', 'setup_build', 'how_to', 'product_page', 'lifestyle', 'pillar']),
    publishDate: z.coerce.date(),
    updatedDate: z.coerce.date().optional(),
    disclosure: z.boolean().default(true),
    schemaType: z.enum(['ItemList', 'Product', 'Article']).default('ItemList'),
    ogImage: z.string().optional(),
    image: z.string().optional(),
    imageAlt: z.string().optional(),
    imageCaption: z.string().optional(),
    imagePosition: z.string().optional(),
    products: z.array(z.object({
      name: z.string(),
      asin: z.string().regex(/^[A-Z0-9]{10}$/),
      bestFor: z.string(),
      blurb: z.string(),
      pros: z.array(z.string()).optional(),
      cons: z.array(z.string()).optional(),
      lookFor: z.array(z.string()).optional(),
      skipIf: z.array(z.string()).optional(),
      smallSpaceNote: z.string().optional(),
      image: z.string().optional(),
      winnieImage: z.string().optional(),
    })).default([]),
    internalLinks: z.array(z.object({ label: z.string(), href: z.string() })).default([]),
    faqs: z.array(z.object({ q: z.string(), a: z.string() })).default([]),
  }),
});

const blog = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string().max(70),
    description: z.string().max(160),
    primaryKeyword: z.string().optional(),
    publishDate: z.coerce.date(),
    updatedDate: z.coerce.date().optional(),
    ogImage: z.string().optional(),
    category: z.string().default('Notes from the nook'),
    image: z.string().default('/winnie/blog-header.jpg'),
    imagePosition: z.string().optional(),
    winniePhoto: z.string().optional(),
    relatedGuides: z.array(z.object({ label: z.string(), href: z.string() })).default([]),
  }),
});

const recipes = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string().max(70),
    description: z.string().max(160),
    primaryKeyword: z.string(),
    publishDate: z.coerce.date(),
    updatedDate: z.coerce.date().optional(),
    category: z.enum(['breakfast', 'main', 'side', 'dessert', 'snack']),
    cuisine: z.string().default('American'),
    prepTimeMinutes: z.number(),
    cookTimeMinutes: z.number(),
    servings: z.number(),
    difficulty: z.enum(['easy', 'intermediate', 'advanced']).default('easy'),
    image: z.string(),
    imageAlt: z.string(),
    imagePosition: z.string().optional(),
    altImage: z.string().optional(),
    altImageAlt: z.string().optional(),
    ingredientsImage: z.string().optional(),
    ingredientsImageAlt: z.string().optional(),
    winnieImage: z.string().optional(),
    winnieNote: z.string().optional(),
    winnieHeadshot: z.string().optional(),
    ingredientGroups: z.array(z.object({
      groupName: z.string().optional(),
      items: z.array(z.union([
        z.string(),
        z.object({
          text: z.string(),
          asin: z.string().regex(/^[A-Z0-9]{10}$/).optional(),
          href: z.string().optional(),
          query: z.string().optional(),
        }),
      ])),
    })),
    instructions: z.array(z.object({ step: z.string() })),
    nutrition: z.object({
      calories: z.number().optional(),
      servingSize: z.string().optional(),
    }).optional(),
    tips: z.array(z.string()).default([]),
    faqs: z.array(z.object({ q: z.string(), a: z.string() })).default([]),
    keywords: z.array(z.string()).default([]),
    disclosure: z.boolean().default(true),
    relatedProducts: z.array(z.object({ label: z.string(), href: z.string() })).default([]),
    relatedRecipes: z.array(z.object({ label: z.string(), href: z.string() })).default([]),
  }),
});

export const collections = { reviews, blog, recipes };
